provider:
  name: faas
  gateway: http://localhost:8080

functions:
  colorization:
    lang: Dockerfile
    handler: ./colorise
    image: developius/openfaas-colorization
    environment:
      read_timeout: 60
      write_timeout: 60
    environment_file:
      - credentials.yml

  normalisecolor:
    lang: Dockerfile
    handler: ./normalisecolor
    image: alexellis2/normalisecolor:0.1
