provider:
  name: faas
  gateway: http://localhost:8080

functions:
  colorization:
    lang: Dockerfile
    handler: ./colorise
    image: alexellis/openfaas-colorization:0.2
    environment:
      read_timeout: 60
      write_timeout: 60
      write_debug: true
    environment_file:
      - credentials.yml

  normalisecolor:
    lang: Dockerfile
    handler: ./normalisecolor
    image: alexellis2/normalisecolor:0.2
